### PR TITLE
Add support to Xcode's New Build System

### PR DESCRIPTION
**Pull request by guilhermearaujo**
Update the podspec to ignore Info.plist, so Xcode can build successfully using its New Build System

### CODE REVIEW

**Comment by mohamede1945** [comment]
thanks

**Comment by guilhermearaujo** [comment]
@mohamede1945 could you please push this updated version to CocoaPods?

**Comment by bj97301** [comment]
@mohamede1945 that should fix this issue: https://github.com/mohamede1945/NextResponderTextField/issues/9

**Comment by mohamede1945** [comment]
Pushed an update to the pod.

**Comment by bj97301** [comment]
Thanks bud.  Let me know if you need help.

**Pull request merged**
